controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      max_vel_x: 0.26
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      critics: ["ObstacleFootprintCritic", "TwirlingCritic", "GoalAlignCritic"]

      ObstacleFootprintCritic:
        scale: 1.0

      TwirlingCritic:
        scale: 1.0

      GoalAlignCritic:
        scale: 1.0