global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    resolution: 0.05
    size_x: 50.0
    size_y: 50.0
    origin_x: -25.0
    origin_y: -25.0
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: laser_scan
      laser_scan:
        topic: /scan
        max_obstacle_height: 2.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    size_x: 3.0
    size_y: 3.0
    origin_x: -1.5
    origin_y: -1.5
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: laser_scan
      laser_scan:
        topic: /scan
        max_obstacle_height: 2.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"